id: AIBO-5cl-eGeMAPS-llds
_target_: autrainer.datasets.AIBO

features_subdir: eGeMAPS-llds-v2
aibo_task: 5cl

path: /data/chi-gpu1/perser/AIBO/
features_path: /data/chi-gpu1/perser/AIBO/features/
index_column: file
target_column: class

file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.UAR

transform:
  type: tabular
  base:
    - autrainer.transforms.Expand:
        size: 301
        axis: -2
  train:
    - autrainer.transforms.RandomCrop:
        size: 301
        axis: -2